name: notion-email-bot
on:
  schedule:
    - cron: "0 9 * * *"   # every day at 9 AM UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install notion-client python-dotenv
      - run: python bot.py --mode daily
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          IMAP_HOST: imap.gmail.com
          IMAP_USER: ${{ secrets.IMAP_USER }}
          IMAP_PASS: ${{ secrets.IMAP_PASS }}
          IMAP_FOLDER: INBOX
          IMAP_SINCE_DAYS: "1"